### ISSUE TITLE
Feature request: middle-click to open in new tab / pane

### ISSUE THREAD

**Issue by sambody** [tgrosinger/recent-files-obsidian#55] opened 2023-03-22 16:46 UTC
I would suggest the ability to open a file in a new tab (new pane) using the middle-click of a mouse. This already works for the default Obsidian file panel, and in the Favorites panel, so it would make sense to make it work here too. 

This is in addition to the suggestions elsewhere (#53 and #28) to use the context-menu for this purpose. 

Thanks

**Comment by tgrosinger** [comment] 2023-05-25 14:35
I agree that it would be nice for middle-click to work. I don't have much time to put into this plugin right now, but pull requests are welcome.

In the mean time, ctrl+click does open it in a new tab.

**Comment by tgrosinger** [comment] 2023-05-25 14:42
I'm going close this as a duplicate of #50.

**Closed by tgrosinger** 2023-05-25 14:42 UTC
