### ISSUE TITLE
Add hover preview over file titles

### ISSUE THREAD

**Issue by classicrob** [tgrosinger/recent-files-obsidian#17] opened 2021-04-18 14:11 UTC
Hi! I use a lot of notes with ZK prefixer so the titles aren't always the most descriptive. Being able to hover preview would be really helpful!

**Comment by tgrosinger** [comment] 2021-04-18 14:51
Seems to be a duplicate of #18.

**Comment by classicrob** [comment] 2021-04-18 15:42
Not a duplicate - the other request is that context is immediately visible as I scroll through it. This is asking for the ability to hover preview and see more context if necessary.

**Comment by tgrosinger** [comment] 2021-04-18 16:11
Ah, I misread. Thanks.

**Comment by tgrosinger** [comment] 2021-04-18 16:12
See comment in https://github.com/tgrosinger/recent-files-obsidian/issues/18#issuecomment-822007664

**Closed** 2021-05-21 14:37 UTC
Labels: enhancement
