### ISSUE TITLE
Selecting a note in the Recent Files will change pinned panels

### ISSUE THREAD

**Issue by Kasuko** [tgrosinger/recent-files-obsidian#13] opened 2021-04-10 02:52 UTC
If I pin a panel to a note and that pinned panel is selected and I select a note from the File Explorer then the note will NOT open in the pinned panel and will open in either an open unpinned panel or a new panel.

However, if I pin a panel to a note and that pinned panel is selected then I select a note from the Recent Files panel then the note WILL open in the pinned panel.

Thus the recent files panel is disregarding the pinned status of a panel. I think it would be ideal if the Recent Files panel respected the pinned panels and followed the same behavior as opening a note via the File Explorer.

**Comment by tgrosinger** [comment] 2021-04-10 03:51
Hello, 
Thanks for reporting the issue. This seems to be a duplicate of #9

**Closed by tgrosinger** 2021-04-10 03:51 UTC

**Comment by Kasuko** [comment] 2021-04-10 04:02
I read that one but I couldn't understand the behavior being described, I was confused by it describing the note opening up in Recent Files panel itself. I haven't experienced a note opening up in the Recent Files panel itself but I have not moved the Recent Files panel.
